run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.gen\\.go$"
    - ".*_generated\\.go$"
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
